MVCWebApp/Models/Person/IPersonRepository.cs
using MVCWebApp.Models.Person.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models.Person
{
    public interface IPersonRepository
    {
        public List<Person> GetAllPersons();
        public Person GetPerson(int id);
        public Person Add(CreatePersonViewModel createPersonViewModel);
        public bool Delete(int id);
        public bool Edit(int? id, EditPersonViewModel editPersonViewModel);
        public bool Edit(EditPersonViewModel editPersonViewModel);
        public List<Person> Search(string searchTerm, bool caseSensitive);
        public List<Person> Sort(SortOptionsViewModel sortOptions, string sortType);

    }
}

MVCWebApp/Models/Person/Person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models.Person
{
    public class Person
    {
        private Person p;

        [Key]
        public int ID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public virtual City.City City { get; set; }
        [Required]
        public string PhoneNumber { get; set; }
        public virtual List<PersonLanguage> PersonLanguages { get; set; }

        public Person()
        {
            PersonLanguages = new List<PersonLanguage>();
        }

        public Person(Person p)
        {
            this.p = p;
        }
    }
}

MVCWebApp/Models/Person/PersonRepository.cs
using Microsoft.EntityFrameworkCore;
using MVCWebApp.Data;
using MVCWebApp.Models.Person.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models.Person
{
    public class PersonRepository : IPersonRepository
    {
        private readonly ApplicationDbContext _context;

        public PersonRepository(ApplicationDbContext context)
        {
            _context = context;
        }

        public List<Person> GetAllPersons()
        {
            _context.Countries.ToList();
            return _context.People.ToList();
        }

        public Person GetPerson(int id)
        {
            return _context.People.Find(id);
        }

        public List<Person> Search(string searchTerm, bool caseSensitive)
        {
            List<Person> searchList = new List<Person>();

            if (searchTerm != null)
            {
                if (caseSensitive)
                {
                    IEnumerable<Person> searchList2 = (from Person in _context.People
                                                      where Person.Name.Contains(searchTerm) || Person.City.CityName.Contains(searchTerm)
                                                      select Person)
                                                      .ToList();

                    //cheat solution case sensitive (database is case insensitive)
                    foreach (Person item in searchList2)
                    {
                        if (item.Name.Contains(searchTerm) || item.City.CityName.Contains(searchTerm))
                        {
                            searchList.Add(item);
                        }
                    }
                }
                else
                {
                    //different way of getting list
                    searchList = _context.People.Where(p => p.City.CityName.Contains(searchTerm) ||
                                                    p.Name.Contains(searchTerm)).ToList();
                }
            }

            return searchList;
        }

        public List<Person> Sort(SortOptionsViewModel sortOptions, string sortType)
        {
            //default by ID
            List<Person> sortedList = _context.People.ToList();

            if (sortType == "city")
            {
                sortedList = _context.People.OrderBy(p => p.City).ToList();
            }
            else if(sortType == "name")
            {
                sortedList = _context.People.OrderBy(p => p.Name).ToList();
            }

            if (sortOptions.ReverseAplhabeticalOrder == true)
            {
                sortedList.Reverse();
            }

            return sortedList;
        }

        public Person Add(CreatePersonViewModel createPersonViewModel)
        {
            Person person = new Person();
            person.Name = createPersonViewModel.Name;
            person.PhoneNumber = createPersonViewModel.PhoneNumber;
            City.City city = _context.Cities.Find(createPersonViewModel.City);
            person.City = city;               

            city.People.Add(person);

            _context.Update(city);
            _context.People.Add(person);
            _context.SaveChanges();

            return person;
        }

        public bool Delete(int id)
        {
            if (id > 0)
            {
                var personToDelete = _context.People.Find(id);

                if (personToDelete != null)
                {
                    _context.People.Remove(personToDelete);
                    _context.SaveChanges();
                    return true;
                }
            }
            return false;
        }

        public bool Edit(int? id, EditPersonViewModel editViewModel)
        {
            if (id != null)
            {
                var personToEdit = _context.People.Find(id);

                if (personToEdit != null)
                {
                    personToEdit.Name = editViewModel.Name;
                    personToEdit.PhoneNumber = editViewModel.PhoneNumber;

                    City.City city = _context.Cities.Find(editViewModel.City);

                    personToEdit.City = city;

                    _context.Entry(personToEdit).State = EntityState.Modified;

                    _context.SaveChanges();
                    return true;
                }
            }
            return false;
        }

        public bool Edit(EditPersonViewModel editViewModel)
        {
            if (editViewModel != null)
            {
                var personToEdit = _context.People.Find(editViewModel.ID);

                if (personToEdit != null)
                {
                    personToEdit.Name = editViewModel.Name;
                    personToEdit.PhoneNumber = editViewModel.PhoneNumber;

                    City.City city = _context.Cities.Find(editViewModel.City);

                    personToEdit.City = city;

                    _context.Entry(personToEdit).State = EntityState.Modified;

                    _context.SaveChanges();
                    return true;
                }
            }
            return false;
        }
    }
}

MVCWebApp/Models/Person/ViewModels/AddLanguageViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models.Person.ViewModels
{
    public class AddLanguageViewModel
    {
        public int PersonId { get; set; }
        public string LanguageName { get; set; }
        public SelectList PersonIdList { get; set; }
        public SelectList LanguageNameList { get; set; }
    }
}

MVCWebApp/Models/Person/ViewModels/CombinedPersonViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models.Person.ViewModels
{
    public class CombinedPersonViewModel
    {
        public IEnumerable<Person> PersonList { get; set; }

        public CreatePersonViewModel CreateViewModel { get; set; }

        public SelectList CityList { get; set; }

        public string SearchTerm { get; set; }

        public SearchPersonViewModel SearchOptions { get; set; }

        public SortOptionsViewModel SortOptions { get; set; }
    }
}

MVCWebApp/Models/Person/ViewModels/CreatePersonViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models.Person.ViewModels
{
    public class CreatePersonViewModel
    {
        [Required]
        [StringLength(40, MinimumLength = 2)]
        public string Name { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "A city must be selected!")]
        public int City { get; set; }

        [Required]
        [RegularExpression(@"[\d]+\-?[\d]+", 
            ErrorMessage = "Please enter a valid phone number! Only numbers and at most one '-'")]
        [StringLength(15, MinimumLength = 7)]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }

        public CreatePersonViewModel() {}
    }
}

MVCWebApp/Models/Person/ViewModels/EditPersonViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models.Person.ViewModels
{
    public class EditPersonViewModel
    {
        [Required]
        public int ID { get; set; }
        [Required]
        [StringLength(40, MinimumLength = 2)]
        public string Name { get; set; }
        [Required]
        [RegularExpression(@"[\d]+\-?[\d]+",
            ErrorMessage = "Please enter a valid phone number! Only numbers and at most one '-'")]
        [StringLength(15, MinimumLength = 7)]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "A city must be selected!")]
        public int City { get; set; }
        public SelectList CityList { get; set; }
        
    }
}

MVCWebApp/Models/Person/ViewModels/PersonLanguagesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Models.Person.ViewModels
{
    public class PersonLanguagesViewModel
    {
        public string PersonName { get; set; }
        public int PersonId { get; set; }
        public List<Language.Language> Languages { get; set; }

        public PersonLanguagesViewModel()
        {
            Languages = new List<Language.Language>();
        }
    }
}

MVCWebApp/Controllers/PersonController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MVCWebApp.Data;
using MVCWebApp.Models;
using MVCWebApp.Models.Language;
using MVCWebApp.Models.Person;
using MVCWebApp.Models.Person.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCWebApp.Controllers
{
    [Authorize]
    public class PersonController : Controller
    {
        private readonly IPersonRepository _personRepository;
        public readonly ApplicationDbContext _context;

        public PersonController(ApplicationDbContext context, IPersonRepository personRepository)
        {
            _context = context;
            _personRepository = personRepository;
        }

        public IActionResult Index()
        {
            CombinedPersonViewModel model = new CombinedPersonViewModel();
            model.PersonList = _personRepository.GetAllPersons();
            model.CityList = new SelectList(_context.Cities.OrderBy(c => c.CityName), "ID", "CityName");

            return View(model);
        }       

        public IActionResult ShowLanguages(int id)
        {
            Person person = _context.People.Find(id);         

            PersonLanguagesViewModel model = new PersonLanguagesViewModel();

            model.PersonName = person.Name;
            model.PersonId = person.ID;

            foreach (PersonLanguage lan in person.PersonLanguages)
            {
                model.Languages.Add(lan.Language);
            }                      

            return View(model);
        }

        public IActionResult AddLanguage()
        {
            AddLanguageViewModel model = new AddLanguageViewModel();
            model.PersonIdList = new SelectList(_context.People, "ID", "Name");
            model.LanguageNameList = new SelectList(_context.Languages, "LanguageName", "LanguageName");

            return View(model);
        }

        [HttpPost]
        public IActionResult AddPersonLanguage(AddLanguageViewModel AddViewModel)
        {          
            Person person = _context.People.Find(AddViewModel.PersonId);

            bool knowsLanguage = false;
            foreach (PersonLanguage pl in person.PersonLanguages)
            {
                if (pl.LanguageName == AddViewModel.LanguageName)
                { 
                    knowsLanguage = true;
                    break;
                }
            }         

            if(knowsLanguage == false)
            {
                Language language = _context.Languages.Find(AddViewModel.LanguageName);

                PersonLanguage personlanguage = new PersonLanguage();
                personlanguage.PersonId = AddViewModel.PersonId;
                personlanguage.LanguageName = AddViewModel.LanguageName;

                person.PersonLanguages.Add(personlanguage);
                language.PersonLanguages.Add(personlanguage);

                _context.PersonLanguages.Add(personlanguage);

                _context.People.Update(person);
                _context.Languages.Update(language);

                _context.SaveChanges();

                PersonLanguage test = _context.PersonLanguages.First();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                //todo - improve
                MessageViewModel messageModel = new MessageViewModel();
                messageModel.Message = "Person already knows that language!";

                return View("MessageView", messageModel);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreatePersonViewModel CreateViewModel)
        {
            if (ModelState.IsValid)
            {
                _personRepository.Add(CreateViewModel);

                return RedirectToAction(nameof(Index));
            }

            CombinedPersonViewModel model = new CombinedPersonViewModel();
            model.PersonList = _personRepository.GetAllPersons();
            model.CityList = new SelectList(_context.Cities, "ID", "CityName");

            return View(nameof(Index), model);
        }

        [Authorize(Roles = "admin")]
        public IActionResult Delete(int id)
        {
            _personRepository.Delete(id);

            CombinedPersonViewModel model = new CombinedPersonViewModel();
            model.PersonList = _personRepository.GetAllPersons();
            model.CityList = new SelectList(_context.Cities, "CityName", "CityName");

            return View(nameof(Index), model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            EditPersonViewModel editPersonViewModel = CreateEditPersonViewModel(id);

            if(editPersonViewModel == null)
                return NotFound();
            else
                return View(editPersonViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EditPersonViewModel editModel)
        {
            if (editModel != null)
            {
                if (ModelState.IsValid)
                {
                    _personRepository.Edit(editModel);
                }
                else
                {
                    return View(CreateEditPersonViewModel(editModel.ID));
                }
            }
            else
                return NotFound();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Search(SearchPersonViewModel searchOptions)
        {

            CombinedPersonViewModel model = new CombinedPersonViewModel();
            model.PersonList = _personRepository.Search(searchOptions.SearchTerm, searchOptions.CaseSensitive);
            model.CityList = new SelectList(_context.Cities, "CityName", "CityName");

            return View(nameof(Index), model);
        }

        [HttpGet]
        public IActionResult SortByCity(SortOptionsViewModel sortOptions)
        {
            CombinedPersonViewModel model = new CombinedPersonViewModel();

            model.PersonList = _personRepository.Sort(sortOptions, "city");
            model.CityList = new SelectList(_context.Cities, "CityName", "CityName");

            return View(nameof(Index), model);
        }

        [HttpGet]
        public IActionResult SortByName(SortOptionsViewModel sortOptions)
        {
            CombinedPersonViewModel model = new CombinedPersonViewModel();

            model.PersonList = model.PersonList = _personRepository.Sort(sortOptions, "name");
            model.CityList = new SelectList(_context.Cities, "CityName", "CityName");

            return View(nameof(Index), model);
        }

        private EditPersonViewModel CreateEditPersonViewModel(int personId)
        {
            Person person = _context.People.Find(personId);

            if (person == null)
                return null;

            EditPersonViewModel model = new EditPersonViewModel();
            model.CityList = new SelectList(_context.Cities, "ID", "CityName", person.City);
            model.City = person.City.ID;
            model.Name = person.Name;
            model.PhoneNumber = person.PhoneNumber;
            model.ID = person.ID;

            return model;
        }
    }
}

MVCWebApp/Views/Person/AddLanguage.cshtml
@model AddLanguageViewModel

@{ ViewData["Title"] = "Add Language to Person"; }
<h1>Add Language View</h1>

<form asp-action="AddPersonLanguage" method="post">
    <div class="form-group">
        <label asp-for="PersonId" class="control-label"></label>
        <select asp-for="PersonId" class="form-control" asp-items="Model.PersonIdList"></select>
    </div>
    <div class="form-group">
        <label asp-for="LanguageName" class="control-label"></label>
        <select asp-for="LanguageName" class="form-control" asp-items="Model.LanguageNameList"></select>
    </div>
    <input type="submit" value="Create" class="btn btn-primary" />
</form>

MVCWebApp/Views/Person/Edit.cshtml
@model EditPersonViewModel

@{ ViewData["Title"] = "Edit Person"; }
<h1>Edit Person</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class=" form-group">
                <input type="hidden" name="id" asp-for="ID" />
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <select asp-for="City" class="form-control" asp-items="Model.CityList"></select>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="create-buttons">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to people</a>
</div>

MVCWebApp/Views/Person/Index.cshtml
@model CombinedPersonViewModel

@{ ViewData["Title"] = "Person List"; }
<h1>PersonIndex</h1>

<form asp-action="AddLanguage" method="post">
    <div class="create-buttons">
        <input type="submit" value="Add Language to a person" class="btn btn-secondary" />
    </div>
</form>

    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="CreateViewModel.Name" class="control-label"></label>
                    <input asp-for="CreateViewModel.Name" class="form-control" />
                    <span asp-validation-for="CreateViewModel.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreateViewModel.City" class="control-label"></label>
                    <select asp-for="CreateViewModel.City" class="form-control" asp-items="Model.CityList"></select>
                    <span asp-validation-for="CreateViewModel.City" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CreateViewModel.PhoneNumber" class="control-label"></label>
                    <input asp-for="CreateViewModel.PhoneNumber" class="form-control" />
                    <span asp-validation-for="CreateViewModel.PhoneNumber" class="text-danger"></span>
                </div>
                <div class="create-buttons">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <form asp-action="Search" method="get">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="SearchOptions.SearchTerm" class="control-label"></label>
                    <input asp-for="SearchOptions.SearchTerm" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="SearchOptions.CaseSensitive" class="control-label"></label>
                    <input asp-for="SearchOptions.CaseSensitive" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <form method="get">
                <div class="form-group">
                    <label asp-for="SortOptions.ReverseAplhabeticalOrder" class="control-label"></label>
                    <input asp-for="SortOptions.ReverseAplhabeticalOrder" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Sort by City" asp-controller="Person"
                           asp-action="SortByCity" class="btn btn-primary" />
                    <input type="submit" value="Sort by Name" asp-controller="Person"
                           asp-action="SortByName" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div class=" personlist container">

        <div class="row align-items-start">

            <div class="col">
                <h4>Name</h4>
            </div>

            <div class="col">
                <h4>City</h4>
            </div>

            <div class="col">
                <h4>Phone Number</h4>
            </div>

            <div class="col">
                <h4>Delete</h4>
            </div>

            <div class="col">
                <h4>Edit</h4>
            </div>

            <div class="col">
                <h4>Languages</h4>
            </div>

        </div>

        @foreach (Person item in Model.PersonList)
        {
<partial name="_partialPersonView" model="item" />}

    </div>

MVCWebApp/Views/Person/ShowLanguages.cshtml
@model PersonLanguagesViewModel

@{ ViewData["Title"] = "Show Person Languages"; }
<h1>Show Person Languages</h1>

<div class="form-group">
    <div class="col">
        <p class="h4">@Model.PersonName knows these languages:</p>
    </div>
</div>

<div class="row align-items-start">
    <div class="col">
        <h4>Language name</h4>
    </div>

    <div class="col">
        <h4>Action</h4>
    </div>
</div>

@foreach (Language lang in Model.Languages)
{
<div class="row align-items-start">

    <div class="col">
        <p>@lang.LanguageName</p>
    </div>

    <div class="col">
        <p>Remove</p>
    </div>

</div>
}